export enum BasicActions {
    GET_ME = 'GET_ME',
    GET_MEDIA = 'GET_MEDIA',
    GET_MEDIA_CHILDREN = 'GET_MEDIA_CHILDREN',
    USER = 'USER',
    USER_MEDIA = 'USER_MEDIA',
}

export enum GraphActions {
    IG_CONTAINER = 'IG_CONTAINER',
    IG_COMMENT = 'IG_COMMENT',
    GET_IG_REPLIES = 'GET_IG_REPLIES',
    POST_IG_REPLIES = 'POST_IG_REPLIES',
    IG_HASHTAG_SEARCH = 'IG_HASHTAG_SEARCH',
    IG_HASHTAG = 'IG_HASHTAG',
    IG_MEDIA = 'IG_MEDIA',
    POST_IG_MEDIA_COMMENTS = 'POST_IG_MEDIA_COMMENTS',
    IG_MEDIA_CHILDREN = 'IG_MEDIA_CHILDREN',
    IG_MEDIA_INSIGHTS = 'IG_MEDIA_INSIGHTS',
    IG_USER = 'IG_USER',
    IG_USER_STORIES = 'IG_USER_STORIES'
}